name: Deploy FastAPI Model to Cloud

# on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Checkout the code from the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub (or other container registry)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set Docker username as GitHub secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set Docker password as GitHub secret

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-ml-model:latest .

    # Push the Docker image to DockerHub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-ml-model:latest

    # Deploy to your cloud provider (for example, AWS ECS, DigitalOcean, etc.)
    # Here's an example for deploying to AWS ECS
    - name: Deploy to AWS ECS
      run: |
        aws ecs update-service \
          --cluster your-cluster-name \
          --service your-service-name \
          --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
